export const AnimationMetaData = {
  cut: {
    name: `cut`,
    frame: 5,
    width: 32,
    height: 32,
    Image: Object.assign(new Image(), { src: './FX/SlashFx/Cut/SpriteSheet.png' }),
    animationSpeed: 5,
    scalingFactor: 2,
  },
  slash: {
    name: `slash`,
    frame: 8,
    width: 32,
    height: 32,
    Image: Object.assign(new Image(), { src: './FX/SlashFx/Slash/SpriteSheet.png' }),
    animationSpeed: 7,
    scalingFactor: 2,
  },
  claw: {
    name: `claw`,
    frame: 8,
    width: 32,
    height: 32,
    Image: Object.assign(new Image(), { src: './FX/SlashFx/Claw/SpriteSheet.png' }),
    animationSpeed: 7,
    scalingFactor: 2,
  },
  claws: {
    name: `claws`,
    frame: 8,
    width: 32,
    height: 32,
    Image: Object.assign(new Image(), { src: './FX/SlashFx/ClawDouble/SpriteSheet.png' }),
    animationSpeed: 7,
    scalingFactor: 2,
  },
  spirit: {
    name: `spirit`,
    frame: 8,
    width: 32,
    height: 32,
    Image: Object.assign(new Image(), { src: './FX/Magic/Spirit/SpriteSheetBlue.png' }),
    animationSpeed: 7,
    scalingFactor: 2,
  },
  spirit2: {
    name: `spirit2`,
    frame: 8,
    width: 32,
    height: 32,
    Image: Object.assign(new Image(), { src: './FX/Magic/Spirit/SpriteSheetDouble.png' }),
    animationSpeed: 7,
    scalingFactor: 2,
  },
  flame: {
    name: `flame`,
    frame: 5,
    width: 32,
    height: 32,
    Image: Object.assign(new Image(), { src: './FX/Elemental/Flam/SpriteSheet.png' }),
    animationSpeed: 7,
    scalingFactor: 2,
  },
  rock: {
    name: `rock`,
    frame: 14,
    width: 30,
    height: 30,
    Image: Object.assign(new Image(), { src: './FX/Elemental/Rock/SpriteSheet.png' }),
    animationSpeed: 5,
    scalingFactor: 2,
  },
  plant: {
    name: `plant`,
    frame: 8,
    width: 30,
    height: 30,
    Image: Object.assign(new Image(), { src: './FX/Elemental/Plant/SpriteSheetB.png' }),
    animationSpeed: 4,
    scalingFactor: 2.2,
  },
  ice: {
    name: `ice`,
    frame: 10,
    width: 32,
    height: 32,
    Image: Object.assign(new Image(), { src: './FX/Elemental/Ice/SpriteSheet.png' }),
    animationSpeed: 5,
    scalingFactor: 2,
  },
  bigice: {
    name: `bigice`,
    frame: 10,
    width: 32,
    height: 32,
    Image: Object.assign(new Image(), { src: './FX/Elemental/Ice/SpriteSheetB.png' }),
    animationSpeed: 4,
    scalingFactor: 2.5,
  },
  fire: {
    name: `fire`,
    frame: 9,
    width: 8,
    height: 12,
    Image: Object.assign(new Image(), { src: './FX/Particle/Fire.png' }),
    animationSpeed: 5,
    scalingFactor: 4.5,
  },
  flower: {
    name: `flower`,
    frame: 8,
    width: 16,
    height: 16,
    Image: Object.assign(new Image(), { src: './Backgrounds/Animated/Plant/SpriteSheet16x16.png' }),
    animationSpeed: 8,
    scalingFactor: 2,
  },
  mill: {
    name: `mill`,
    frame: 4,
    width: 64,
    height: 64,
    Image: Object.assign(new Image(), { src: './Backgrounds/Animated/MillPropeller/MillPropeller_B_64x64.png' }),
    animationSpeed: 6,
    scalingFactor: 3,
  },
  wmill: {
    name: `wmill`,
    frame: 3,
    width: 34,
    height: 36,
    Image: Object.assign(new Image(), { src: './Backgrounds/Animated/WaterMill/Watermill_B_34x36.png' }),
    animationSpeed: 6,
    scalingFactor: 3,
  }
}
