export const AnimationMetaData = {
  cut: {
    name: `cut`,
    frame: 5,
    width: 32,
    height: 32,
    Image: Object.assign(new Image(), { src: './FX/SlashFx/Cut/SpriteSheet.png' }),
    animationSpeed: 5,
    scalingFactor: 2,
  },
  slash: {
    name: `slash`,
    frame: 8,
    width: 32,
    height: 32,
    Image: Object.assign(new Image(), { src: './FX/SlashFx/Slash/SpriteSheet.png' }),
    animationSpeed: 8,
    scalingFactor: 2,
  },
  claw: {
    name: `claw`,
    frame: 8,
    width: 32,
    height: 32,
    Image: Object.assign(new Image(), { src: './FX/SlashFx/Claw/SpriteSheet.png' }),
    animationSpeed: 8,
    scalingFactor: 2,
  },
  powerClaw: {
    name: `powerClaw`,
    frame: 8,
    width: 32,
    height: 32,
    Image: Object.assign(new Image(), { src: './FX/SlashFx/ClawDouble/SpriteSheet.png' }),
    animationSpeed: 8,
    scalingFactor: 2,
  },
  spirit: {
    name: `spirit`,
    frame: 8,
    width: 32,
    height: 32,
    Image: Object.assign(new Image(), { src: './FX/Magic/Spirit/SpriteSheet.png' }),
    animationSpeed: 8,
    scalingFactor: 2,
  },
  spirit2: {
    name: `spirit2`,
    frame: 8,
    width: 32,
    height: 32,
    Image: Object.assign(new Image(), { src: './FX/Magic/Spirit/SpriteSheetDouble.png' }),
    animationSpeed: 8,
    scalingFactor: 2,
  },
  flame: {
    name: `flame`,
    frame: 5,
    width: 32,
    height: 32,
    Image: Object.assign(new Image(), { src: './FX/Elemental/Flam/SpriteSheet.png' }),
    animationSpeed: 8,
    scalingFactor: 2,
  },
  rock: {
    name: `rock`,
    frame: 14,
    width: 32,
    height: 32,
    Image: Object.assign(new Image(), { src: './FX/Elemental/Rock/SpriteSheet.png' }),
    animationSpeed: 8,
    scalingFactor: 2,
  },
  ice: {
    name: `ice`,
    frame: 10,
    width: 32,
    height: 32,
    Image: Object.assign(new Image(), { src: './FX/Elemental/Ice/SpriteSheet.png' }),
    animationSpeed: 8,
    scalingFactor: 2,
  },
  grass: {
    name: `grass`,
    frame: 6,
    width: 8,
    height: 8,
    Image: Object.assign(new Image(), { src: './FX/Particle/Grass.png' }),
    animationSpeed: 8,
    scalingFactor: 2,
  },
  fire: {
    name: `fire`,
    frame: 12,
    width: 16,
    height: 16,
    Image: Object.assign(new Image(), { src: './FX/Particle/Fire.png' }),
    animationSpeed: 8,
    scalingFactor: 2,
  },
  plant: {
    name: `plant`,
    frame: 8,
    width: 16,
    height: 16,
    Image: Object.assign(new Image(), { src: './Backgrounds/Animated/Plant/SpriteSheet16x16.png' }),
    animationSpeed: 8,
    scalingFactor: 2,
  },
  flower: {
    name: `flower`,
    frame: 2,
    width: 16,
    height: 16,
    Image: Object.assign(new Image(), { src: './Backgrounds/Animated/Flower/SpriteSheet16x16.png' }),
    animationSpeed: 8,
    scalingFactor: 2,
  },
  mill: {
    name: `mill`,
    frame: 8,
    width: 16,
    height: 16,
    Image: Object.assign(new Image(), { src: './Backgrounds/Animated/MillPropeller/MillPropeller_B_64x64.png' }),
    animationSpeed: 8,
    scalingFactor: 2,
  },
  water: {
    name: `water`,
    frame: 8,
    width: 16,
    height: 16,
    Image: Object.assign(new Image(), { src: './Backgrounds/Animated/Water Ripples/SpriteSheet16x16.png' }),
    animationSpeed: 8,
    scalingFactor: 2,
  },
  wmill: {
    name: `wmill`,
    frame: 8,
    width: 16,
    height: 16,
    Image: Object.assign(new Image(), { src: './Backgrounds/Animated/WaterMill/Watermill_B_34x36.png' }),
    animationSpeed: 8,
    scalingFactor: 2,
  }
}
