
export const EnemyMetaData = {
  mouse: {
    name: `mouse`,
    Image: Object.assign(new Image(), { src: "./Actor/Monsters/Mouse/SpriteSheet.png" }),
    Speed: 1.25,
    Range: 140,
    Hp: 10,
    Attack: 1,
    Score: 2,
    ani: 'claw',
  },
  snake: {
    name: `snake`,
    Image: Object.assign(new Image(), { src: "./Actor/Monsters/Snake/Snake.png" }),
    Speed: 1.75,
    Range: 195,
    Hp: 30,
    Attack: 1,
    Score: 3,
    ani: 'claw',
  },
  racoon: {
    name: `racoon`,
    Image: Object.assign(new Image(), { src: "./Actor/Monsters/Racoon/SpriteSheet.png" }),
    Speed: 2.75,
    Range: 155,
    Hp: 30,
    Attack: 1,
    Score: 3,
    ani: 'claw',
  },
  bamboo: {
    name: `bamboo`,
    Image: Object.assign(new Image(), { src: "./Actor/Monsters/Bamboo/SpriteSheet.png" }),
    Speed: 1.75,
    Range: 155,
    Hp: 60,
    Attack: 1,
    Score: 5,
    ani: 'plant',
  },
  mushroom: {
    name: `mushroom`,
    Image: Object.assign(new Image(), { src: "./Actor/Monsters/Mushroom/mushroom.png" }),
    Speed: 2.125,
    Range: 175,
    Hp: 40,
    Attack: 2,
    Score: 5,
    ani: 'plant',
  },
  axolot: {
    name: `axolot`,
    Image: Object.assign(new Image(), { src: "./Actor/Monsters/Axolot/SpriteSheet.png" }),
    Speed: 1.8,
    Range: 165,
    Hp: 120,
    Attack: 1,
    Score: 5,
    ani: 'claw',
  },
  eye: {
    name: `eye`,
    Image: Object.assign(new Image(), { src: "./Actor/Monsters/Eye/Eye2.png" }),
    Speed: 1.8,
    Range: 215,
    Hp: 60,
    Attack: 1,
    Score: 3,
    ani: 'cut',
  },
  spirit: {
    name: `spirit`,
    Image: Object.assign(new Image(), { src: "./Actor/Monsters/Spirit/SpriteSheet.png" }),
    Speed: 2.8,
    Range: 165,
    Hp: 60,
    Attack: 1,
    Score: 3,
    ani: 'claws',
  },
  skull: {
    name: `skull`,
    Image: Object.assign(new Image(), { src: "./Actor/Monsters/Skull/SpriteSheet.png" }),
    Speed: 2.2,
    Range: 185,
    Hp: 80,
    Attack: 2,
    Score: 5,
    ani: 'flame',
  },

  //snow
  larva: {
    name: `larva`,
    Image: Object.assign(new Image(), { src: "./Actor/Monsters/Larva/Larva2.png" }),
    Speed: 1.9,
    Range: 225,
    Hp: 90,
    Attack: 1,
    Score: 3,
    ani: 'claw',
  },
  slime: {
    name: `slime`,
    Image: Object.assign(new Image(), { src: "./Actor/Monsters/Slime/Slime.png" }),
    Speed: 2.9,
    Range: 175,
    Hp: 90,
    Attack: 1,
    Score: 3,
    ani: 'ice',
  },
  owl: {
    name: `owl`,
    Image: Object.assign(new Image(), { src: "./Actor/Monsters/Owl/Owl.png" }),
    Speed: 1.9,
    Range: 175,
    Hp: 180,
    Attack: 1,
    Score: 5,
    ani: 'slash',
  },
  flame: {
    name: `flame`,
    Image: Object.assign(new Image(), { src: "./Actor/Monsters/Flam/SpriteSheet.png" }),
    Speed: 2.3,
    Range: 195,
    Hp: 120,
    Attack: 2,
    Score: 5,
    ani: 'ice',
  },

  beast: {
    name: `beast`,
    Image: Object.assign(new Image(), { src: "./Actor/Monsters/Beast2/Beast2.png" }),
    Speed: 2.9,
    Range: 220,
    Hp: 200,
    Attack: 2,
    Score: 20,
    ani: 'rock',
  },
  skeleton: {
    name: `skeleton`,
    Image: Object.assign(new Image(), { src: "./Actor/Monsters/Skeleton/SpriteSheet.png" }),
    Speed: 3.2,
    Range: 230,
    Hp: 120,
    Attack: 2,
    Score: 20,
    ani: 'claws',
  },
  boss: {
    name: `boss`,
    Image: Object.assign(new Image(), { src: "./Actor/Boss/SpriteSheet.png" }),
    Speed: 2,
    Range: 550,
    Hp: 500,
    Attack: 0,
    Score: 100,
    ani: 'claw',
  },
}
