
export const EnemyMetaData = {
  mouse: {
    name: `mouse`,
    Image: Object.assign(new Image(), { src: "./Actor/Monsters/Mouse/SpriteSheet.png" }),
    Speed: 1.2,
    Range: 150,
    Hp: 10,
    Attack: 1,
    ani: 'claw',
  },
  snake: {
    name: `snake`,
    Image: Object.assign(new Image(), { src: "./Actor/Monsters/Snake/Snake.png" }),
    Speed: 2,
    Range: 200,
    Hp: 30,
    Attack: 1,
    ani: 'claw',
  },
  racoon: {
    name: `racoon`,
    Image: Object.assign(new Image(), { src: "./Actor/Monsters/Racoon/SpriteSheet.png" }),
    Speed: 1.6,
    Range: 250,
    Hp: 30,
    Attack: 1,
    ani: 'claw',
  },
  bamboo: {
    name: `bamboo`,
    Image: Object.assign(new Image(), { src: "./Actor/Monsters/Bamboo/SpriteSheet.png" }),
    Speed: 2,
    Range: 200,
    Hp: 80,
    Attack: 1,
    ani: 'claw',
  },
  mushroom: {
    name: `mushroom`,
    Image: Object.assign(new Image(), { src: "./Actor/Monsters/Mushroom/mushroom.png" }),
    Speed: 1.8,
    Range: 150,
    Hp: 60,
    Attack: 2,
    ani: 'claw',
  },
  axolot: {
    name: `axolot`,
    Image: Object.assign(new Image(), { src: "./Actor/Monsters/Axolot/SpriteSheet.png" }),
    Speed: 1.8,
    Range: 200,
    Hp: 100,
    Attack: 2,
    ani: 'claw',
  },
  spirit: {
    name: `spirit`,
    Image: Object.assign(new Image(), { src: "./Actor/Monsters/Siprit/SpriteSheet.png" }),
    Speed: 1.8,
    Range: 200,
    Hp: 100,
    Attack: 2,
    ani: 'claw',
  },
  Eye: {
    name: `spirit`,
    Image: Object.assign(new Image(), { src: "./Actor/Monsters/Eye/Eye2.png" }),
    Speed: 1.8,
    Range: 200,
    Hp: 100,
    Attack: 2,
    ani: 'claw',
  },
  skull: {
    name: `skull`,
    Image: Object.assign(new Image(), { src: "./Actor/Monsters/Skull/SpriteSheet.png" }),
    Speed: 1,
    Range: 450,
    Hp: 1000,
    Attack: 2,
    ani: 'claw',
  },

  //snow
  larva: {
    name: `larva`,
    Image: Object.assign(new Image(), { src: "./Actor/Monsters/Flam2/SpriteSheet.png" }),
    Speed: 2.5,
    Range: 300,
    Hp: 50,
    Attack: 2,
    ani: 'claw',
  },
  flame: {
    name: `flame`,
    Image: Object.assign(new Image(), { src: "./Actor/Monsters/Flam/SpriteSheet.png" }),
    Speed: 2.5,
    Range: 300,
    Hp: 50,
    Attack: 2,
    ani: 'claw',
  },
  slime: {
    name: `slime`,
    Image: Object.assign(new Image(), { src: "./Actor/Monsters/Slime/Slime.png" }),
    Speed: 2.5,
    Range: 300,
    Hp: 50,
    Attack: 2,
    ani: 'claw',
  },
  owl: {
    name: `owl`,
    Image: Object.assign(new Image(), { src: "./Actor/Monsters/Owl/owl.png" }),
    Speed: 2.5,
    Range: 300,
    Hp: 50,
    Attack: 2,
    ani: 'claw',
  },

  beast: {
    name: `beast`,
    Image: Object.assign(new Image(), { src: "./Actor/Monsters/Beast2/Beast2.png" }),
    Speed: 2.5,
    Range: 300,
    Hp: 50,
    Attack: 3,
    ani: 'claw',
  },
  skeleton: {
    name: `skeleton`,
    Image: Object.assign(new Image(), { src: "./Actor/Monsters/Skeleton/SpriteSheet.png" }),
    Speed: 2.5,
    Range: 300,
    Hp: 50,
    Attack: 3,
    ani: 'claw',
  },
}
