export const EnemyMetaData = {
  mouse: {
    name: `mouse`,
    Image: Object.assign(new Image(), {
      src: "./Actor/Monsters/Mouse/SpriteSheet.png",
      alt: "mouse",
    }),
    Speed: 1.2,
    Range: 140,
    Hp: 10,
    Attack: 1,
    Score: 2,
    ani: "claw",
  },
  snake: {
    name: `snake`,
    Image: Object.assign(new Image(), {
      src: "./Actor/Monsters/Snake/Snake.png",
      alt: "snake",
    }),
    Speed: 1.7,
    Range: 190,
    Hp: 30,
    Attack: 1,
    Score: 3,
    ani: "claw",
  },
  racoon: {
    name: `racoon`,
    Image: Object.assign(new Image(), {
      src: "./Actor/Monsters/Racoon/SpriteSheet.png",
      alt: "racoon",
    }),
    Speed: 2.5,
    Range: 150,
    Hp: 30,
    Attack: 1,
    Score: 3,
    ani: "claw",
  },
  bamboo: {
    name: `bamboo`,
    Image: Object.assign(new Image(), {
      src: "./Actor/Monsters/Bamboo/SpriteSheet.png",
      alt: "bamboo",
    }),
    Speed: 1.7,
    Range: 150,
    Hp: 60,
    Attack: 1,
    Score: 5,
    ani: "plant",
  },
  mushroom: {
    name: `mushroom`,
    Image: Object.assign(new Image(), {
      src: "./Actor/Monsters/Mushroom/mushroom.png",
      alt: "mushroom",
    }),
    Speed: 2,
    Range: 170,
    Hp: 40,
    Attack: 2,
    Score: 5,
    ani: "plant",
  },
  axolot: {
    name: `axolot`,
    Image: Object.assign(new Image(), {
      src: "./Actor/Monsters/Axolot/SpriteSheet.png",
      alt: "axolot",
    }),
    Speed: 1.7,
    Range: 170,
    Hp: 120,
    Attack: 1,
    Score: 5,
    ani: "claw",
  },
  eye: {
    name: `eye`,
    Image: Object.assign(new Image(), {
      src: "./Actor/Monsters/Eye/Eye2.png",
      alt: "eye",
    }),
    Speed: 1.7,
    Range: 210,
    Hp: 60,
    Attack: 1,
    Score: 3,
    ani: "cut",
  },
  spirit: {
    name: `spirit`,
    Image: Object.assign(new Image(), {
      src: "./Actor/Monsters/Spirit/SpriteSheet.png",
      alt: "spirit",
    }),
    Speed: 2.6,
    Range: 170,
    Hp: 60,
    Attack: 1,
    Score: 3,
    ani: "claws",
  },
  skull: {
    name: `skull`,
    Image: Object.assign(new Image(), {
      src: "./Actor/Monsters/Skull/SpriteSheet.png",
      alt: "skull",
    }),
    Speed: 2.1,
    Range: 180,
    Hp: 80,
    Attack: 2,
    Score: 5,
    ani: "flame",
  },

  //snow
  larva: {
    name: `larva`,
    Image: Object.assign(new Image(), {
      src: "./Actor/Monsters/Larva/Larva2.png",
      alt: "larva",
    }),
    Speed: 1.8,
    Range: 230,
    Hp: 80,
    Attack: 1,
    Score: 3,
    ani: "claw",
  },
  slime: {
    name: `slime`,
    Image: Object.assign(new Image(), {
      src: "./Actor/Monsters/Slime/Slime.png",
      alt: "slime",
    }),
    Speed: 2.7,
    Range: 180,
    Hp: 80,
    Attack: 1,
    Score: 3,
    ani: "ice",
  },
  owl: {
    name: `owl`,
    Image: Object.assign(new Image(), {
      src: "./Actor/Monsters/Owl/Owl.png",
      alt: "owl",
    }),
    Speed: 1.8,
    Range: 180,
    Hp: 140,
    Attack: 1,
    Score: 5,
    ani: "slash",
  },
  flame: {
    name: `flame`,
    Image: Object.assign(new Image(), {
      src: "./Actor/Monsters/Flam/SpriteSheet.png",
      alt: "flame",
    }),
    Speed: 2.2,
    Range: 200,
    Hp: 120,
    Attack: 2,
    Score: 5,
    ani: "ice",
  },

  beast: {
    name: `beast`,
    Image: Object.assign(new Image(), {
      src: "./Actor/Monsters/Beast2/Beast2.png",
      alt: "beast",
    }),
    Speed: 2.7,
    Range: 220,
    Hp: 200,
    Attack: 2,
    Score: 20,
    ani: "rock",
  },
  skeleton: {
    name: `skeleton`,
    Image: Object.assign(new Image(), {
      src: "./Actor/Monsters/Skeleton/SpriteSheet.png",
      alt: "skeleton",
    }),
    Speed: 2.9,
    Range: 280,
    Hp: 120,
    Attack: 2,
    Score: 20,
    ani: "claws",
  },
  boss: {
    name: `boss`,
    Image: Object.assign(new Image(), {
      src: "./Actor/Boss/SpriteSheet.png",
      alt: "boss",
    }),
    Speed: 1.7,
    Range: 600,
    Hp: 500,
    Attack: 2,
    Score: 100,
    ani: "bigice",
  },
};
