export const ItemMetaData = {
  spear: {
    name: 'spear',
    kind: 'weapon',
    Image: Object.assign(new Image(), { src: './Items/Weapons/Spear/Sprite.png' }),
    height: 28,
    width: 7,
    audio: 'weapon',
    scalingFactor: 4.2,
    frame: 1,
    animationSpeed: 8,
  },
  bow: {
    name: 'bow',
    kind: 'weapon',
    Image: Object.assign(new Image(), { src: './Items/Weapons/Bow/icon.png' }),
    image: '',
    height: 16,
    width: 12,
    audio: 'weapon',
    scalingFactor: 4,
    frame: 1,
    animationSpeed: 8,
  },
  sword: {
    name: 'sword',
    kind: 'weapon',
    Image: Object.assign(new Image(), { src: './Items/Weapons/Sword/Sprite.png' }),
    image: '',
    height: 20,
    width: 6,
    audio: 'weapon',
    scalingFactor: 4,
    frame: 1,
    animationSpeed: 8,
  },
  axe: {
    name: 'axe',
    kind: 'weapon',
    Image: Object.assign(new Image(), { src: './Items/Weapons/Axe/Sprite.png' }),
    image: '',
    height: 21,
    width: 11,
    audio: 'weapon',
    scalingFactor: 4,
    frame: 1,
    animationSpeed: 8,
  },
  shuriken: {
    name: 'shuriken',
    kind: 'weapon',
    Image: Object.assign(new Image(), { src: './FX/Projectile/Shuriken.png' }),
    image: '',
    height: 16,
    width: 16,
    audio: 'weapon',
    scalingFactor: 3,
    frame: 1,
    animationSpeed: 8,
  },
  staff: {
    name: 'staff',
    kind: 'weapon',
    Image: Object.assign(new Image(), { src: './Items/Weapons/Staff/Sprite.png' }),
    height: 21,
    width: 5,
    audio: 'weapon',
    scalingFactor: 4,
    frame: 1,
    animationSpeed: 8,
  },
  coin: {
    name: 'coin',
    kind: 'score',
    Image: Object.assign(new Image(), { src: './Items/Treasure/Coin2.png' }),
    height: 10,
    width: 10,
    audio: 'coin',
    scalingFactor: 3,
    frame: 4,
    score: 10,
    animationSpeed: 8
  },
  potion: {
    name: 'potion',
    kind: 'potion',
    Image: Object.assign(new Image(), { src: './Items/Potion/LifePot.png' }),
    height: 12,
    width: 10,
    audio: 'weapon',
    scalingFactor: 4,
    frame: 1,
    animationSpeed: 8
  },
  sushi: {
    name: 'sushi',
    kind: 'food',
    Image: Object.assign(new Image(), { src: './Items/Food/Sushi2.png' }),
    height: 16,
    width: 16,
    audio: 'food',
    scalingFactor: 3.5,
    frame: 1,
    animationSpeed: 8,
  },
  honey: {
    name: 'honey',
    kind: 'food',
    Image: Object.assign(new Image(), { src: './Items/Food/Honey.png' }),
    height: 16,
    width: 16,
    audio: 'food',
    scalingFactor: 3.5,
    frame: 1,
    animationSpeed: 8,
  },
  yakitori: {
    name: 'yakitori',
    kind: 'food',
    Image: Object.assign(new Image(), { src: './Items/Food/Yakitori.png' }),
    height: 16,
    width: 16,
    audio: 'food',
    scalingFactor: 3.5,
    frame: 1,
    animationSpeed: 8,
  },
  onigiri: {
    name: 'onigiri',
    kind: 'food',
    Image: Object.assign(new Image(), { src: './Items/Food/Onigiri.png' }),
    height: 16,
    width: 16,
    audio: 'food',
    scalingFactor: 3.5,
    frame: 1,
    animationSpeed: 8,
  },
  beaf: {
    name: 'beaf',
    kind: 'food',
    Image: Object.assign(new Image(), { src: './Items/Food/Beaf.png' }),
    height: 16,
    width: 16,
    audio: 'food',
    scalingFactor: 3.5,
    frame: 1,
    animationSpeed: 8,
  },
  seed: {
    name: 'seed',
    kind: 'food',
    Image: Object.assign(new Image(), { src: './Items/Food/SeedBig1.png' }),
    height: 16,
    width: 16,
    audio: 'food',
    scalingFactor: 3.5,
    frame: 1,
    animationSpeed: 8,
  },
  fish: {
    name: 'fish',
    kind: 'food',
    Image: Object.assign(new Image(), { src: './Items/Food/Fish.png' }),
    height: 16,
    width: 16,
    audio: 'food',
    scalingFactor: 3.5,
    frame: 1,
    animationSpeed: 8,
  },
  cup: {
    name: 'cup',
    kind: 'score',
    Image: Object.assign(new Image(), { src: './Items/Treasure/GoldCup.png' }),
    height: 12,
    width: 12,
    scalingFactor: 4,
    frame: 1,
    score: 100,
    animationSpeed: 8,
  },
  letter: {
    name: 'letter',
    kind: 'letter',
    Image: Object.assign(new Image(), { src: './Items/Other/Letter.png' }),
    height: 12,
    width: 12,
    scalingFactor: 3.8,
    frame: 1,
    score: 100,
    animationSpeed: 8,
  },
}
