export const NpcMetaData = {
  boy: {
    name: 'boy',
    Image: Object.assign(new Image(), { src: '/Actor/Npc/Boy/SpriteSheet.png' }),
    speed: 1.2,
    range: 60,
    height: 16,
    width: 16,
    scalingFactor: 3.6,
  },
  inspector: {
    name: 'inspector',
    Image: Object.assign(new Image(), { src: '/Actor/Npc/Inspector/SpriteSheet.png' }),
    speed: 0.8,
    range: 40,
    height: 16,
    width: 16,
    scalingFactor: 3.8,
  },
  knight: {
    name: 'knight',
    Image: Object.assign(new Image(), { src: '/Actor/Npc/Knight/SpriteSheet.png' }),
    speed: 1.2,
    range: 100,
    height: 16,
    width: 16,
    scalingFactor: 4,
  },
  master: {
    name: 'master',
    Image: Object.assign(new Image(), { src: '/Actor/Npc/Master/SpriteSheet.png' }),
    speed: 1,
    range: 100,
    height: 16,
    width: 16,
    scalingFactor: 3.6,
  },
  monk: {
    name: 'monk',
    Image: Object.assign(new Image(), { src: '/Actor/Npc/Monk/SpriteSheet.png' }),
    speed: 1,
    range: 60,
    height: 16,
    width: 16,
    scalingFactor: 3.6,
  },
  oldman1: {
    name: 'oldman1',
    Image: Object.assign(new Image(), { src: '/Actor/Npc/OldMan/SpriteSheet.png' }),
    speed: 0.7,
    range: 45,
    height: 16,
    width: 16,
    scalingFactor: 4,
  },
  oldman2: {
    name: 'oldman2',
    Image: Object.assign(new Image(), { src: '/Actor/Npc/OldMan2/SpriteSheet.png' }),
    speed: 0.6,
    range: 20,
    height: 16,
    width: 16,
    scalingFactor: 4.2,
  },
  snow: {
    name: 'snow',
    Image: Object.assign(new Image(), { src: '/Actor/Npc/Snow/SpriteSheet.png' }),
    speed: 1,
    range: 100,
    height: 16,
    width: 16,
    scalingFactor: 4,
  },
  snowbaby: {
    name: 'snowbaby',
    Image: Object.assign(new Image(), { src: '/Actor/Npc/Snow/SpriteSheet.png' }),
    speed: 1,
    range: 100,
    height: 16,
    width: 16,
    scalingFactor: 3.4,
  },
  villager1: {
    name: 'villager1',
    Image: Object.assign(new Image(), { src: '/Actor/Npc/Villager/SpriteSheet.png' }),
    speed: 0.8,
    range: 30,
    height: 16,
    width: 16,
    scalingFactor: 3.6,
  },
  villager2: {
    name: 'villager2',
    Image: Object.assign(new Image(), { src: '/Actor/Npc/Villager3/SpriteSheet.png' }),
    speed: 1,
    range: 80,
    height: 16,
    width: 16,
    scalingFactor: 4,
  },
  villager3: {
    name: 'villager3',
    Image: Object.assign(new Image(), { src: '/Actor/Npc/Villager4/SpriteSheet.png' }),
    speed: 1,
    range: 70,
    height: 16,
    width: 16,
    scalingFactor: 3.8,
  },
  woman: {
    name: 'woman',
    Image: Object.assign(new Image(), { src: '/Actor/Npc/Woman/SpriteSheet.png' }),
    speed: 1,
    range: 70,
    height: 16,
    width: 16,
    scalingFactor: 4,
  },
}
