export const WeaponMetaData = {
  axe: {
    type: `melee`,
    name: `axe`,
    height: 21,
    width: 11,
    audio: 'melee',
    damage: 30,
    Image: Object.assign(new Image(), { src: './Items/Weapons/Axe/Sprite2.png' }),
    ani: 'cut',
  },
  bow: {
    type: `range`,
    name: `bow`,
    height: 8,
    width: 16,
    audio: 'range',
    damage: 0,
    Image: Object.assign(new Image(), { src: './Items/Weapons/Bow/Sprite.png' }),
    ani: 'slash',
    Projectile: {
      Image: Object.assign(new Image(), { src: './FX/Projectile/Arrow2.png' }),
      ani: 'slash',
      damage: 15,
      height: 15,
      width: 15,
      frames: 2,
      duration: 1,
      speed: 15,
      decrementRate: 0.14,
      name: `arrow`,
    }
  },
  shuriken: {
    type: `range`,
    name: `shuriken`,
    height: 24,
    width: 6,
    audio: 'range',
    damage: 5,
    Image: Object.assign(new Image(), { src: '' }),
    ani: 'slash',
    Projectile: {
      Image: Object.assign(new Image(), { src: './FX/Projectile/Shuriken.png' }),
      ani: 'slash',
      damage: 10,
      height: 16,
      width: 16,
      frames: 2,
      duration: 4,
      speed: 11,
      decrementRate: 0.12,
      name: `shuriken`,
    }
  },
  sword: {
    type: `melee`,
    name: `sword`,
    height: 20,
    width: 6,
    audio: 'melee',
    damage: 15,
    Image: Object.assign(new Image(), { src: './Items/Weapons/Sword/Sprite2.png' }),
    ani: 'cut',
  },
  staff: {
    type: `range`,
    name: `staff`,
    height: 21,
    width: 5,
    audio: 'fire',
    damage: 20,
    Image: Object.assign(new Image(), { src: './Items/Weapons/Staff/Sprite.png' }),
    ani: 'flame',
    Projectile: {
      Image: Object.assign(new Image(), { src: './FX/Projectile/Fireball2.png' }),
      damage: 25,
      ani: 'flame',
      height: 16,
      width: 16,
      frames: 4,
      duration: 4,
      speed: 11,
      decrementRate: 0.06,
      name: `fireBall`,
    }
  },
  spear: {
    type: `melee`,
    name: `spear`,
    height: 28,
    width: 7,
    audio: 'melee',
    damage: 20,
    Image: Object.assign(new Image(), { src: './Items/Weapons/Spear/Sprite2.png' }),
    ani: 'cut',
  },
}
