export const AnimalMetaData = {
  cow: {
    name: 'cow',
    Image: Object.assign(new Image(), { src: './Actor/Animals/Cow/SpriteSheet2.png' }),
    speed: 1,
    size: true,
    range: 100,
    height: 16,
    width: 24,
  },
  horse: {
    name: 'horse',
    Image: Object.assign(new Image(), { src: './Actor/Animals/Horse/SpriteSheet1.png' }),
    speed: 1.2,
    size: true,
    range: 175,
    height: 16,
    width: 23,
  },
  orangeLion: {
    name: 'orangeLion',
    Image: Object.assign(new Image(), { src: './Actor/Animals/Lion/SpriteSheetOrange2.png' }),
    speed: 1.35,
    size: true,
    range: 150,
    height: 16,
    width: 35,
  },
  whiteLion: {
    name: 'whiteLion',
    Image: Object.assign(new Image(), { src: './Actor/Animals/Lion/SpriteSheetWhite2.png' }),
    speed: 1.35,
    size: true,
    range: 150,
    height: 16,
    width: 35,
  },
  dog: {
    name: `dog`,
    Image: Object.assign(new Image(), { src: './Actor/Animals/Dog/SpriteSheet2.png' }),
    speed: 2,
    range: 100,
    height: 16,
    width: 16,
  },
  frog: {
    name: `frog`,
    Image: Object.assign(new Image(), { src: './Actor/Animals/Frog/SpriteSheet2.png' }),
    speed: 0.8,
    range: 20,
    height: 16,
    width: 16,
  },
  brownChicken: {
    name: `brownChicked`,
    Image: Object.assign(new Image(), { src: './Actor/Animals/Chicken/SpriteSheetBrown2.png' }),
    speed: 1.5,
    range: 120,
    height: 16,
    width: 16,
  },
  blackChicken: {
    name: `blackChicken`,
    Image: Object.assign(new Image(), { src: './Actor/Animals/Chicken/SpriteSheetCute2.png' }),
    speed: 1.75,
    range: 80,
    height: 16,
    width: 16,
  },
  whiteChicken: {
    name: `whiteChicken`,
    Image: Object.assign(new Image(), { src: './Actor/Animals/Chicken/SpriteSheetWhite2.png' }),
    speed: 1.5,
    range: 120,
    height: 16,
    width: 16,
  },
  pig: {
    name: `pig`,
    Image: Object.assign(new Image(), { src: './Actor/Animals/Pig/SpriteSheet2.png' }),
    speed: 1.3,
    size: true,
    range: 60,
    height: 16,
    width: 16,
  }
}
