
export const EnemyMetaData = {
  snake: {
    name: `snake`,
    Image: Object.assign(new Image(), { src: "./Actor/Monsters/Snake/Snake.png" }),
    Speed: 2,
    Range: 300,
    Hp: 30,
    Attack: 1,
    ani: 'claw',
  },
  racoon: {
    name: `racoon`,
    Image: Object.assign(new Image(), { src: "./Actor/Monsters/GoldRacoon/SpriteSheet.png" }),
    Speed: 1.6,
    Range: 200,
    Hp: 60,
    Attack: 1,
    ani: 'claw',
  },
  mouse: {
    name: `mouse`,
    Image: Object.assign(new Image(), { src: "./Actor/Monsters/Mouse/SpriteSheet.png" }),
    Speed: 1.2,
    Range: 200,
    Hp: 10,
    Attack: 1,
    ani: 'claw',
  },
  bamboo: {
    name: `bamboo`,
    Image: Object.assign(new Image(), { src: "./Actor/Monsters/BambooYellow/SpriteSheet.png" }),
    Speed: 2,
    Range: 250,
    Hp: 60,
    Attack: 1,
    ani: 'claw',
  },
  mushroom: {
    name: `mushroom`,
    Image: Object.assign(new Image(), { src: "./Actor/Monsters/Mushroom/mushroom.png" }),
    Speed: 1.8,
    Range: 200,
    Hp: 100,
    Attack: 2,
    ani: 'claw',
  },
  lizard: {
    name: `lizard`,
    Image: Object.assign(new Image(), { src: "./Actor/Monsters/Lizard/Lizard.png" }),
    Speed: 2.5,
    Range: 300,
    Hp: 50,
    Attack: 1,
    ani: 'claw',
  },
  skull: {
    name: `skull`,
    Image: Object.assign(new Image(), { src: "./Actor/Monsters/Skull/SpriteSheet.png" }),
    Speed: 1,
    Range: 450,
    Hp: 1000,
    Attack: 2,
    ani: 'claw',
  },
  flame: {
    name: `flame`,
    Image: Object.assign(new Image(), { src: "./Actor/Monsters/Flam2/SpriteSheet.png" }),
    Speed: 2.5,
    Range: 300,
    Hp: 50,
    Attack: 2,
    ani: 'claw',
  },
  beast: {
    name: `beast`,
    Image: Object.assign(new Image(), { src: "./Actor/Monsters/Beast2/Beast2.png" }),
    Speed: 2.5,
    Range: 300,
    Hp: 50,
    Attack: 3,
    ani: 'claw',
  },
}
