export const BackgroundAudio = [
  {
    name: 'village',
    audio: ['./Musics/4 - Village.ogg'],
    volume: 0.3,
    loop: true,
  },
  {
    name: 'cave',
    audio: ['./Musics/2 - The Cave.ogg'],
    volume: 0.3,
    loop: true,
  },
  {
    name: 'peaceful',
    audio: ['./Musics/5 - Peaceful.ogg'],
    volume: 0.45,
    loop: true,
  },
  {
    name: 'sad',
    audio: ['./Musics/7 - Sad Theme.ogg'],
    volume: 0.7,
    loop: true,
  },
  {
    name: 'chill',
    audio: ['./Musics/27 - Chill.ogg'],
    volume: 0.3,
    loop: true,
  },
  {
    name: 'adventure',
    audio: ['./Musics/1 - Adventure Begin.ogg'],
    volume: 0.3,
    loop: true,
  },
  {
    name: 'adventure2',
    audio: ['./Musics/16 - Melancholia.ogg'],
    volume: 0.3,
    loop: true,
  },
  {
    name: 'quiet',
    audio: ['./Musics/9 - Quiet.ogg'],
    volume: 0.3,
    loop: true,
  },
  {
    name: 'castle',
    audio: ['./Musics/10 - Dark Castle.ogg'],
    volume: 0.3,
    loop: true,
  },
  {
    name: 'temple',
    audio: ['./Musics/12 - Temple.ogg'],
    volume: 0.3,
    loop: true,
  },
  {
    name: 'mystical',
    audio: ['./Musics/13 - Mystical.ogg'],
    volume: 0.3,
    loop: true,
  },
  {
    name: 'dungeon',
    audio: ['./Musics/21 - Dungeon.ogg'],
    volume: 0.3,
    loop: true,
  },
  {
    name: 'road',
    audio: ['./Musics/23 - Road.ogg'],
    volume: 0.3,
    loop: true,
  },
  {
    name: 'lost',
    audio: ['./Musics/26 - Lost Village.ogg'],
    volume: 0.3,
    loop: true,
  },
  {
    name: 'ruins',
    audio: ['./Musics/30 - Ruins.ogg'],
    volume: 0.3,
    loop: true,
  },
]
