export const BackgroundAudio = [
  {
    name: 'village',
    audio: ['/Sound/BackgroundMusic/4.mp3'],
    volume: 0.3,
    loop: true,
    type: 'bg',
  },
  {
    name: 'cave',
    audio: ['/Sound/BackgroundMusic/2.mp3'],
    volume: 0.3,
    loop: true,
    type: 'bg',
  },
  {
    name: 'peaceful',
    audio: ['/Sound/BackgroundMusic/5.mp3'],
    volume: 0.4,
    loop: true,
    type: 'bg',
  },
  {
    name: 'sad',
    audio: ['/Sound/BackgroundMusic/7.mp3'],
    volume: 0.7,
    loop: true,
    type: 'bg',
  },
  {
    name: 'chill',
    audio: ['/Sound/BackgroundMusic/27.mp3'],
    volume: 0.3,
    loop: true,
    type: 'bg',
  },
  {
    name: 'adventure',
    audio: ['/Sound/BackgroundMusic/1.mp3'],
    volume: 0.2,
    loop: true,
    type: 'bg',
  },
  {
    name: 'adventure2',
    audio: ['/Sound/BackgroundMusic/16.mp3'],
    volume: 0.3,
    loop: true,
    type: 'bg',
  },
  {
    name: 'quiet',
    audio: ['/Sound/BackgroundMusic/9.mp3'],
    volume: 0.3,
    loop: true,
    type: 'bg',
  },
  {
    name: 'castle',
    audio: ['/Sound/BackgroundMusic/10.mp3'],
    volume: 0.3,
    loop: true,
    type: 'bg',
  },
  {
    name: 'temple',
    audio: ['/Sound/BackgroundMusic/12.mp3'],
    volume: 0.3,
    loop: true,
    type: 'bg',
  },
  {
    name: 'mystical',
    audio: ['/Sound/BackgroundMusic/13.mp3'],
    volume: 0.3,
    loop: true,
    type: 'bg',
  },
  {
    name: 'dungeon',
    audio: ['/Sound/BackgroundMusic/21.mp3'],
    volume: 0.3,
    loop: true,
    type: 'bg',
  },
  {
    name: 'road',
    audio: ['/Sound/BackgroundMusic/23.mp3'],
    volume: 0.3,
    loop: true,
    type: 'bg',
  },
  {
    name: 'lost',
    audio: ['/Sound/BackgroundMusic/26.mp3'],
    volume: 0.3,
    loop: true,
    type: 'bg',
  },
  {
    name: 'ruins',
    audio: ['/Sound/BackgroundMusic/30.mp3'],
    volume: 0.3,
    loop: true,
    type: 'bg',
  },
  {
    name: 'final',
    audio: ['/Sound/BackgroundMusic/24.mp3'],
    volume: 0.3,
    loop: true,
    type: 'bg',
  },
]
